/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package agebot;

import com.slack.api.bolt.App;
import com.slack.api.bolt.AppConfig;
import com.slack.api.bolt.socket_mode.SocketModeApp;

import java.util.Properties;
import java.util.regex.Pattern;

public class Application {
    public static void main(String[] args) throws Exception {
        //Write your code here
        String dateString = "1999-04-14";
        int age = calculateAge(dateString);
        System.out.printf("Age based on input date %s is %d%n", dateString, age);
    }
}
